version: '3'
services:
  frontend:
    image: privatesumelabdesarrollo/frontfactura:latest
    ports:
      - "80:80"

  backend:
    image: privatesumelabdesarrollo/apifacturacion:latest
    ports:
      - "8081:8081"
    environment:
      TZ: "America/Guayaquil"
