version: '3'
services:
  frontend:
    image: sumelabdesarrollo/frontfactura:latest
    ports:
      - "4200:80"

  backend:
    image: sumelabdesarrollo/apifacturacion:latest
    ports:
      - "8081:8081"
    environment:
      TZ: "America/Guayaquil"
