version: '3'
services:
  frontend:
    image: sumelabdesarrollo/factura_front:latest
    ports:
      - "4200:4200"

  backend:
    image: sumelabdesarrollo/apifacturacion:latest
    ports:
      - "8081:8081"
    environment:
      TZ: "America/Guayaquil"
